# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cfdd3e76c657fa7e6f0c98f424fb8955"
name = "FluxChat AI Assistant"
application_url = "https://0fa1c7eac933.ngrok-free.app:3458"
embedded = true
handle = "flux-chat"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders,read_customers"

[auth]
redirect_urls = ["https://0fa1c7eac933.ngrok-free.app:3458/auth/callback", "https://0fa1c7eac933.ngrok-free.app:3458/auth/shopify/callback", "https://0fa1c7eac933.ngrok-free.app:3458/api/auth/callback"]

[pos]
embedded = false

[app_proxy]
url = "https://0fa1c7eac933.ngrok-free.app:3458"
subpath = "flux-chat"
prefix = "apps"
